### PR TITLE
Reference docs structure improvements

### PR DESCRIPTION
**Pull request by peyerluk**
## Changelog

- 🔥 🎁 🎉 Completely restructure reference-docs (too many changes to list here)
- 🎁 Added video tour from `developers.livingdocs.io` to 'Learn'
- 🎁 Improved boilerplate evaluation guide: renamed it to 'On Premise Setup' and tried to clarify that boilerplates need access
- 🍬 Style `vimeo` shortcode
- 🍬 Add `github` shortcode
- 🍬 Add `warning` shortcode
- 🖊️ Extend README (titles, shortcodes, icons)
- 🎨 Widen page on large screens and left align page (still needs some improvement)
- 🎨 Remove negative left padding for code examples

### CODE REVIEW

**Comment by peyerluk** [comment]
FYI: @svenlivingdocs I did a few design changes and additions in this PR.

**Review by DaRaFF — APPROVED** [review]
The structure is much better, I like it!

**Comment by DaRaFF** [comment]
@marcbachmann I had a problem with the local hugo version of the documentation.
When I start the doc with `npm run start`, the documentation opens at `https://localhost:1313/`, but the editor is only reachable at `http://0.0.0.0:1313/` with all it's links. It works for me only, when I start the doc with `npm run start -- -b http://0.0.0.0:1313`. Have you an idea how to fix that issue?

**Comment by svenlivingdocs** [comment]
> FYI: @svenlivingdocs I did a few design changes and additions in this PR.

👍 Will take a look later today.

**Comment by gabrielhase** [comment]
@peyerluk Is this what you showed yesterday? If so:
- please leave "developers.livingdocs.io" as is online until we have a better solution for the service vs. boilerplate issue
- webhooks should go to public API
- ideally public API should move to this documentation here and the link in the editor should link to this documentation here as well

**Pull request merged**
